// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/egandro/news-deframer/pkg/openai (interfaces: OpenAI)
//
// Generated by this command:
//
//	mockgen -destination=./mock_openai/mocks.go github.com/egandro/news-deframer/pkg/openai OpenAI
//

// Package mock_openai is a generated GoMock package.
package mock_openai

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOpenAI is a mock of OpenAI interface.
type MockOpenAI struct {
	ctrl     *gomock.Controller
	recorder *MockOpenAIMockRecorder
	isgomock struct{}
}

// MockOpenAIMockRecorder is the mock recorder for MockOpenAI.
type MockOpenAIMockRecorder struct {
	mock *MockOpenAI
}

// NewMockOpenAI creates a new mock instance.
func NewMockOpenAI(ctrl *gomock.Controller) *MockOpenAI {
	mock := &MockOpenAI{ctrl: ctrl}
	mock.recorder = &MockOpenAIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenAI) EXPECT() *MockOpenAIMockRecorder {
	return m.recorder
}

// FuzzyParseJSON mocks base method.
func (m *MockOpenAI) FuzzyParseJSON(input string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FuzzyParseJSON", input)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FuzzyParseJSON indicates an expected call of FuzzyParseJSON.
func (mr *MockOpenAIMockRecorder) FuzzyParseJSON(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FuzzyParseJSON", reflect.TypeOf((*MockOpenAI)(nil).FuzzyParseJSON), input)
}

// Query mocks base method.
func (m *MockOpenAI) Query(ctx context.Context, user, system string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, user, system)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockOpenAIMockRecorder) Query(ctx, user, system any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockOpenAI)(nil).Query), ctx, user, system)
}
